# Generated by Django 2.2 on 2020-05-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='settings',
            field=models.TextField(default='{"assassins_ending": false}'),
        ),
    ]
